name: build

on:
  push:
    paths: 
      - '**.js'

jobs:
  build:
    name: "Node.js Build Workflow"
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
        exclude:
          - os: macos-latest
            node-version: 12.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Setup Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node-version }}
      - name: "Install necessary Node packages"
        run: npm ci
      - name: "Build the Node.js code"
        run: npm run build --if-present
